apiVersion: apps/v1
kind: Deployment
metadata:
  name: velos-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: velos-api
  template:
    metadata:
      labels:
        app: velos-api
    spec:
      containers:
      - name: velos-api
        image: brinet12/velos-api:1.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: db-secret
        readinessProbe:
          httpGet:
            path: /sante
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /sante
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: velos-api-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30081
  selector:
    app: velos-api
