apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "velos"
  DB_USER: "velo_user"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS stations (
        id SERIAL PRIMARY KEY,
        nom VARCHAR(100) NOT NULL,
        velos_disponibles INT NOT NULL,
        emplacements_libres INT NOT NULL
    );
    INSERT INTO stations (nom, velos_disponibles, emplacements_libres) VALUES
        ('Gare Centrale', 5, 10),
        ('Place du Commerce', 0, 15),
        ('Université', 2, 8),
        ('Parc des Sports', 8, 2);
